# Generated by Django 4.2.2 on 2023-07-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='week_activity',
            field=models.TextField(blank=True),
        ),
    ]
