# Generated by Django 4.2.2 on 2023-07-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
        migrations.AddField(
            model_name='logbook',
            name='week_activity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='logbook_print_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='practical_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
