# Generated by Django 4.2.2 on 2023-07-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_logbook_week_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='practical_training_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
