# Generated by Django 4.2.2 on 2023-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_remove_entry_rating_logbook_week_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='All Entries updated ?'),
        ),
    ]
