# Generated by Django 4.2.2 on 2023-07-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_entry_is_updated_alter_logbook_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='activity_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='activity_diagrams'),
        ),
    ]
