# Generated by Django 4.2.2 on 2023-07-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_student_practical_training_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
    ]
