# Generated by Django 4.2.2 on 2023-07-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_logbook_activity_diagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='activity_diagram',
            field=models.FileField(blank=True, null=True, upload_to='activity_diagrams'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='All Entries updated'),
        ),
    ]
