# Generated by Django 4.2.2 on 2023-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_remove_entry_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='logbook_print_count',
            field=models.IntegerField(default=0),
        ),
    ]
