# Generated by Django 4.2.2 on 2023-07-27 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_alter_logbook_activity_diagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Logbook Printed'),
        ),
        migrations.CreateModel(
            name='Week_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.TextField(blank=True)),
                ('machinery', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_operations', to='logbook.logbook')),
            ],
        ),
    ]
