# Generated by Django 4.2.2 on 2023-07-28 18:43

from django.db import migrations, models
import logbook.models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_alter_logbook_is_submitted_week_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='activity_diagram',
            field=models.FileField(blank=True, default=logbook.models.get_default_activity_diagram, upload_to='activity_diagrams'),
        ),
    ]
